namespace StatementDelivery.Domain.Abstractions;

/// <summary>
/// Produces primary keys. Every identifier in this system is generated by the application, never
/// by a column DEFAULT.
/// </summary>
/// <remarks>
/// <para>
/// This port lives in the domain and is implemented in the adapters
/// (<c>StatementDelivery.Persistence.Ids.UuidV7Generator</c>). The domain decides that identity is
/// supplied rather than assigned by the database; the adapter decides that the supplied value is a
/// UUIDv7. Inverting that - putting the interface next to its implementation - would force every
/// factory that mints an identity to reach into the persistence layer.
/// </para>
/// <para>
/// Application generation is also what lets an aggregate and its outbox message share an identity
/// inside one transaction without a round trip.
/// </para>
/// <para>
/// SECURITY: for database keys only. UUIDv7 embeds a timestamp and is therefore partially
/// predictable. Download tokens must NOT use it - they are 256-bit CSPRNG values with no
/// structure. See docs/adr/0006-uuidv7-primary-keys.md.
/// </para>
/// </remarks>
public interface IIdGenerator
{
    /// <summary>
    /// Returns a new identifier that sorts after every identifier previously returned by this
    /// instance, compared in big-endian byte order.
    /// </summary>
    Guid NewId();
}
