namespace StatementDelivery.Contracts;

/// <summary>
/// Marker contract for an event published across a service boundary.
/// </summary>
/// <remarks>
/// <para>
/// Integration events are the only shape allowed to cross a service boundary. They are
/// versioned by type name, serialised as JSON, and carried through the transactional
/// outbox so that "state changed" and "event published" commit or fail together.
/// </para>
/// <para>
/// Nothing implements this yet. It exists so that the outbox contracts in
/// StatementDelivery.Messaging have something to constrain against, and so that the first
/// real event lands in the right assembly rather than wherever it was convenient.
/// </para>
/// </remarks>
public interface IIntegrationEvent
{
    /// <summary>
    /// Gets the unique identity of this event occurrence. UUIDv7, generated by the producer.
    /// </summary>
    /// <remarks>
    /// Consumers use this for idempotent de-duplication: the outbox guarantees at-least-once
    /// delivery, so a consumer will eventually see the same identifier twice.
    /// </remarks>
    Guid EventId { get; }

    /// <summary>
    /// Gets the instant the event occurred, as recorded by the producer. Always UTC.
    /// </summary>
    DateTimeOffset OccurredAt { get; }
}
