-- =============================================================================================
-- V004  Transactional outbox.
--
-- Writing an integration event to this table inside the SAME transaction as the state change is
-- what removes the dual-write failure: either both commit or neither does. A relay then publishes
-- what it finds here, at least once.
--
-- Partitioned BY RANGE on created_at, DAILY. A published, past-grace-period day is removed with
-- DROP TABLE rather than DELETE. At this system's volumes that difference is not cosmetic: DELETE
-- leaves dead tuples for vacuum to reclaim, churns WAL, and competes for I/O with the very
-- generation burst that produced the rows. DROP TABLE is near-instant and writes almost no WAL.
-- =============================================================================================

CREATE TABLE IF NOT EXISTS outbox
(
    -- UUIDv7, generated by the application (see BuildingBlocks/Persistence/Ids). Time-ordered, so
    -- the relay reads the backlog in insertion order as an index range scan rather than a sort,
    -- and inserts land at the right edge of the index instead of fragmenting it.
    -- Deliberately no DEFAULT: the application always supplies the value, so an aggregate and its
    -- outbox row can share an identity before either is written.
    id            UUID        NOT NULL,

    -- The RANGE partition key. Also the relay's read order.
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Contract name used to resolve the deserialisation target. Renaming a published event type
    -- is a breaking change; add a new type instead.
    event_type    TEXT        NOT NULL,

    -- jsonb, not json: it is stored parsed, so a malformed payload is rejected at write time
    -- rather than discovered by a consumer at 3am.
    payload       JSONB       NOT NULL,

    -- W3C traceparent captured at write time. This is what keeps a trace connected across the
    -- asynchronous boundary. Without it the consumer starts a new, unrelated trace, and the causal
    -- chain breaks at exactly the point where an operator most needs it.
    trace_parent  TEXT        NULL,

    -- NULL while pending. The partial index below is defined on this, so the relay's working set
    -- stays small no matter how large the partition grows.
    published_at  TIMESTAMPTZ NULL,

    attempt_count INTEGER     NOT NULL DEFAULT 0,

    -- A partitioned table's primary key MUST include the partition key. The consequence worth
    -- knowing: this enforces uniqueness of (id, created_at), not of id alone across partitions.
    -- For a 128-bit UUIDv7 that is an acceptable trade; for a sequence-derived key it would not be.
    CONSTRAINT pk_outbox PRIMARY KEY (id, created_at),
    CONSTRAINT ck_outbox_event_type CHECK (length(event_type) BETWEEN 1 AND 256),
    CONSTRAINT ck_outbox_attempts   CHECK (attempt_count >= 0)
)
PARTITION BY RANGE (created_at);

COMMENT ON TABLE outbox IS
    'Transactional outbox. Daily RANGE partitions; published days are removed with DROP TABLE, never DELETE.';
COMMENT ON COLUMN outbox.trace_parent IS
    'W3C traceparent captured at write time so the trace survives the asynchronous boundary.';

ALTER TABLE outbox OWNER TO app_migrator;

-- The relay's only query: oldest unpublished first. PARTIAL, so the index holds only the pending
-- backlog - typically a few thousand rows - rather than every event ever written. A full index on
-- created_at would grow with the table and be almost entirely dead weight.
CREATE INDEX IF NOT EXISTS ix_outbox_pending
    ON outbox (created_at, id)
    WHERE published_at IS NULL;

-- ---------------------------------------------------------------------------------------------
-- Grants.
--
-- Producers INSERT. The relay UPDATEs to mark published. Only app_retention may DELETE, and even
-- it should be dropping whole partitions rather than deleting rows - the DELETE grant exists for
-- the exceptional single-row case, not for routine cleanup.
-- ---------------------------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE         ON outbox TO app_generation;
GRANT SELECT, INSERT                 ON outbox TO app_delivery;
GRANT SELECT                         ON outbox TO app_download;
GRANT SELECT, UPDATE, DELETE         ON outbox TO app_retention;

-- ---------------------------------------------------------------------------------------------
-- Initial partitions.
--
-- Creating the parent alone would leave a table that accepts no writes at all: the first INSERT
-- would fail with "no partition of relation outbox found for row". Seven days ahead matches the
-- Partitioning:PeriodsAhead default the maintenance service and the readiness check both use.
-- ---------------------------------------------------------------------------------------------
SELECT ensure_range_partitions('outbox'::regclass, 'day', 7);
